#!/bin/bash
# 🧬 [自动生成] 体液受体挂载 (Alias)
BASHRC="$HOME/.bashrc"
echo -e "📝 正在清理并重植 ~/.bashrc 别名基因..."
sed -i '/alias noa=/d' "$BASHRC"
sed -i '/alias noa-approve=/d' "$BASHRC"
sed -i '/alias noa-log=/d' "$BASHRC"
sed -i '/alias noa-tui=/d' "$BASHRC"
sed -i '/alias noa-install=/d' "$BASHRC"
echo "alias noa='bash /home/hashi/noa/dna/noa_cli.sh'" >> "$BASHRC"
echo "alias noa-approve='python3 /home/hashi/noa/dna/device_manager.py'" >> "$BASHRC"
echo "alias noa-log='tail -f /home/hashi/noa/thalamus.log'" >> "$BASHRC"
echo "alias noa-tui='python3 /home/hashi/noa/dna/local_tui.py'" >> "$BASHRC"
echo "alias noa-install='bash /home/hashi/noa/dna/install.sh'" >> "$BASHRC"
echo -e "✅ Alias 别名挂载成功！"
